# Generated by Django 3.1.2 on 2020-10-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='product_id',
            new_name='customer_id',
        ),
    ]
