# Generated by Django 3.1.2 on 2020-10-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201030_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_date',
            new_name='order_date',
        ),
    ]
